apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: order-service
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:PASSWORD@db.ygxoxqmagowztruehtgi.supabase.co:5432/postgres"
  DATABASE_USERNAME: "postgres"
  DATABASE_PASSWORD: "YOUR_PASSWORD_HERE"
