version: '3.8'

services:
  order-service:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    env_file:
      - ../../.env
    networks:
      - order-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/orders/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  order-network:
    driver: bridge
